#!/usr/bin/env python3
"""
Google Geocoding Script for Philadelphia Historical Synagogues
Geocodes 157 historical addresses and generates SQL UPDATE statements
"""

import requests
import time
import csv
import sys

# Configuration

API_KEY = "AIzaSyBxqGTP-pITv_Rv0FBXTV48Gi0ms8kTDIU"
INPUT_FILE = "addresses_to_geocode.csv"
OUTPUT_SQL = "geocoding_updates.sql"
DELAY_BETWEEN_REQUESTS = 0.1  # seconds (to respect rate limits)

def geocode_address(address, api_key):
    """Geocode a single address using Google Geocoding API"""
    base_url = "https://maps.googleapis.com/maps/api/geocode/json"
    
    params = {
        'address': address,
        'key': api_key
    }
    
    try:
        response = requests.get(base_url, params=params)
        response.raise_for_status()
        data = response.json()
        
        if data['status'] == 'OK':
            location = data['results'][0]['geometry']['location']
            return {
                'latitude': location['lat'],
                'longitude': location['lng'],
                'formatted_address': data['results'][0]['formatted_address'],
                'status': 'OK'
            }
        else:
            return {
                'latitude': None,
                'longitude': None,
                'formatted_address': None,
                'status': data['status']
            }
    except Exception as e:
        return {
            'latitude': None,
            'longitude': None,
            'formatted_address': None,
            'status': f'ERROR: {str(e)}'
        }

def main():
    if API_KEY == "YOUR_GOOGLE_API_KEY_HERE":
        print("ERROR: Please set your Google API key in the script!")
        print("Replace YOUR_GOOGLE_API_KEY_HERE with your actual API key")
        sys.exit(1)
    
    # Read addresses
    print(f"Reading {INPUT_FILE}...")
    with open(INPUT_FILE, 'r') as f:
        reader = csv.DictReader(f)
        addresses = list(reader)
    
    print(f"Found {len(addresses)} addresses to geocode")
    print("Starting geocoding...\n")
    
    results = []
    
    for i, row in enumerate(addresses, 1):
        synagogue = row['synagogue']
        address = row['full_address']
        
        print(f"[{i}/{len(addresses)}] {synagogue}")
        print(f"  Address: {address}")
        
        # Geocode
        result = geocode_address(address, API_KEY)
        
        if result['status'] == 'OK':
            print(f"  ✓ Success: {result['latitude']}, {result['longitude']}")
        else:
            print(f"  ✗ Failed: {result['status']}")
        
        results.append({
            'synagogue': synagogue,
            'address': address,
            'latitude': result['latitude'],
            'longitude': result['longitude'],
            'status': result['status']
        })
        
        # Rate limiting
        time.sleep(DELAY_BETWEEN_REQUESTS)
        print()
    
    # Generate SQL UPDATE statements
    print(f"\nGenerating SQL file: {OUTPUT_SQL}")
    
    with open(OUTPUT_SQL, 'w') as f:
        f.write("-- ============================================================================\n")
        f.write("-- GEOCODING UPDATES - 157 Historical Addresses\n")
        f.write("-- ============================================================================\n")
        f.write("-- This file contains UPDATE statements to add lat/lon to historical addresses\n")
        f.write("-- Generated by geocoding script\n")
        f.write("-- ============================================================================\n\n")
        
        success_count = 0
        failed_count = 0
        
        for i, result in enumerate(results, 1):
            synagogue = result['synagogue'].replace("'", "''")  # Escape quotes
            address = result['address'].replace("'", "''")
            
            if result['latitude'] and result['longitude']:
                f.write(f"-- {i}. {result['synagogue']} (SUCCESS)\n")
                f.write(f"UPDATE public.addresses\n")
                f.write(f"SET latitude = {result['latitude']},\n")
                f.write(f"    longitude = {result['longitude']}\n")
                f.write(f"WHERE synagogue_id = (\n")
                f.write(f"    SELECT id FROM public.synagogues WHERE name = '{synagogue}' LIMIT 1\n")
                f.write(f"  )\n")
                f.write(f"  AND street_address = '{address.split(';')[0].strip()}'\n")
                f.write(f"  AND latitude IS NULL;\n\n")
                success_count += 1
            else:
                f.write(f"-- {i}. {result['synagogue']} (FAILED: {result['status']})\n")
                f.write(f"-- Address: {result['address']}\n")
                f.write(f"-- TODO: Manual geocoding needed\n\n")
                failed_count += 1
        
        f.write(f"\n-- ============================================================================\n")
        f.write(f"-- SUMMARY\n")
        f.write(f"-- ============================================================================\n")
        f.write(f"-- Total addresses: {len(results)}\n")
        f.write(f"-- Successfully geocoded: {success_count}\n")
        f.write(f"-- Failed: {failed_count}\n")
        f.write(f"-- ============================================================================\n")
    
    print(f"\n{'='*80}")
    print("GEOCODING COMPLETE")
    print(f"{'='*80}")
    print(f"Total addresses: {len(results)}")
    print(f"Successfully geocoded: {success_count}")
    print(f"Failed: {failed_count}")
    print(f"\nSQL file created: {OUTPUT_SQL}")
    print(f"\nNext steps:")
    print(f"1. Review {OUTPUT_SQL}")
    print(f"2. Run it in Supabase SQL Editor or TablePlus")
    print(f"3. Verify coordinates were added")

if __name__ == "__main__":
    main()
